name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build_bmv2:
    runs-on: ubuntu-latest
    
    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@v1
 
      - uses: actions/checkout@v2
      
      - name: Add artifact dir
        run: mkdir out
      
      - name: List dir
        run: ls -lah 
        
      - name: Execute bmv2 build script 
        run: ./compile_bmv2.sh
      
      - uses: actions/upload-artifact@v2
        with:
          name: bmv2_binary
          path: out/
